# Generated by Django 3.1.4 on 2020-12-03 03:36

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogme', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 3, 3, 36, 42, 970841, tzinfo=utc)),
        ),
    ]
