# Generated by Django 3.1.4 on 2020-12-04 03:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blogme', '0002_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 12, 4, 3, 50, 36, 313184, tzinfo=utc)),
        ),
    ]
